finish/frontendUI/src/main/java/io/openliberty/guides/ui/ApplicationBean.java
finish/frontendUI/src/main/java/io/openliberty/guides/ui/models/SystemModel.java
finish/frontendUI/src/main/java/io/openliberty/guides/ui/util/ServiceUtils.java
finish/frontendUI/src/main/webapp/application.xhtml
start/frontendUI/src/main/java/io/openliberty/guides/ui/ApplicationBean.java
start/frontendUI/src/main/java/io/openliberty/guides/ui/models/SystemModel.java
start/frontendUI/src/main/java/io/openliberty/guides/ui/util/ServiceUtils.java
start/frontendUI/src/main/webapp/application.xhtml

Frontend Improvements

---

README.adoc

Changed mvnpackage.adoc to mvncompile.adoc

---

finish/frontendUI/src/main/java/io/openliberty/guides/ui/LoginBean.java
finish/frontendUI/src/main/webapp/WEB-INF/web.xml
start/frontendUI/src/main/java/io/openliberty/guides/ui/LoginBean.java
start/frontendUI/src/main/webapp/WEB-INF/web.xml

Steps to reproduce the problem on the current master branch:
1. Start server
1. Login
1. Go to login page (without logging out)
1. Stop server
1. Start server
1. Login
1. See Exception
If you perform these steps on this branch, then you should not see this error.
Additionally, I made a change such that it logs you out before you login because previously you got an error message if you try to login while you're already logged in. I did this since sessions don't appear to remain valid after the server restarts, so the application page would be in an invalid state anyway.

Fix View State Error

---

finish/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/backendServices/src/test/java/it/io/openliberty/guides/jwt/util/JwtVerifier.java
finish/frontendUI/pom.xml

Unused imports, indirect static access and version redundancy

Minor IDE warnings adressed

---

finish/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
finish/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/backendServices/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
start/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
start/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
start/backendServices/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java
start/backendServices/src/main/java/io/openliberty/guides/inventory/model/SystemData.java

OpenLiberty/guides-common#95
OpenLiberty/guides-common#137

Refactor inventory

---

README.adoc
finish/backendServices/pom.xml
finish/backendServices/src/main/liberty/config/server.xml
finish/frontendUI/pom.xml
finish/frontendUI/src/main/liberty/config/server.xml
finish/pom.xml
finish/resources/pom.xml
start/backendServices/pom.xml
start/frontendUI/pom.xml
start/frontendUI/src/main/liberty/config/server.xml
start/pom.xml
start/resources/pom.xml

- Update feature versions
- Convert dependencies
- Update README

Updating feature versions and converting dependencies

---

finish/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
finish/backendServices/src/main/java/io/openliberty/guides/inventory/client/SecureSystemClient.java
finish/backendServices/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java
start/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
start/backendServices/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java

Make thread-safety changes

---

finish/backendServices/pom.xml
finish/pom.xml
start/backendServices/pom.xml
start/pom.xml

Addressing: https://github.com/OpenLiberty/guides-common/issues/268

Updated pom.xml in start & finish to reduce warnings in messages.log

---

README.adoc
finish/backendServices/pom.xml
finish/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/backendServices/src/main/java/io/openliberty/guides/inventory/JwtResource.java
finish/backendServices/src/main/java/io/openliberty/guides/inventory/client/SecureSystemClient.java
finish/backendServices/src/main/java/io/openliberty/guides/system/SystemResource.java
finish/backendServices/src/main/liberty/config/server.xml
finish/backendServices/src/test/java/it/io/openliberty/guides/jwt/InventoryEndpointTest.java
finish/backendServices/src/test/java/it/io/openliberty/guides/jwt/JwtTest.java
finish/backendServices/src/test/java/it/io/openliberty/guides/jwt/SystemEndpointTest.java
start/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
start/backendServices/src/main/java/io/openliberty/guides/system/SystemResource.java

* Changed from replace to update on first tag
* Updated hotspots and changed file styles
* minor fixes
* Nimrah's Fixes
* More fixes
* changed hide tag copyright
* testing on lgdev
* Final fix for Nimrah's issue
* Actual final fix
* Actual actual final fix
* updated licensing and copyright date
* Updated licensing, added start/ comments, removed server.xml creation title
* Spacing fixes

Merge qa to master: Updating guide formatting (#96)

---

README.adoc

Qa to master: hotspot fix

---

README.adoc

Merge qa to master: update a word

---

README.adoc
finish/backendServices/pom.xml
finish/backendServices/src/main/liberty/config/server.xml
start/backendServices/pom.xml

Merge qa to master: update pom.xml to use transportSecurity-1.0

---

finish/frontendUI/src/main/webapp/application.xhtml
start/frontendUI/src/main/webapp/application.xhtml

addressed issue outlined here: https://github.com/OpenLiberty/guide-microprofile-jwt/issues/70

table word wrap fix

---

README.adoc

Addressing https://github.com/openliberty/guides-common/issues/514

added cd commands

---

README.adoc

Addressing https://github.com/OpenLiberty/guide-microprofile-jwt/issues/135

Content Review

---

.github/workflows/test.yaml
CONTRIBUTING.md

- add back the CONTRIBUTING.md
- update the test.yaml

Merge qa to master: restore the CONTRIBUTING.md file

---

.github/workflows/test.yaml
finish/frontend/src/main/webapp/application.xhtml
scripts/dailyBuild.sh
scripts/testApp.sh
start/frontend/src/main/webapp/application.xhtml

* fixing word wrap issue
* update column sizes
* switching column width to 20/80
* add contribution file
* Update to work with daily builds
* Change LMP version
* Change test script
* Revert pom changes
* Update daily build script
* Prepare for daily builds
* Update test script
* Update dailyBuild.sh
* Fix sed command
* Update test.yaml
* Update test.yaml
* Revert `application.xhtml` into what it currently is in default branch
* Fix line breaks
* Spacing adjustment
Co-authored-by: Tiago Ferreira <t.ferreiraibm.com@Tiagos-MacBook-Pro.local>
Co-authored-by: Gilbert Kwan <gkwan@ca.ibm.com>
Co-authored-by: DannyS03 <danny.salman@ryerson.ca>
Co-authored-by: Austin Seto <austin.seto@ibm.com>

Merge qa to master: GH Actions (#142)

---

README.adoc

* Fixing related guides section.
* fixing links in guide
* Fixing hotspots

Merge qa to master: Fixing related guides section (#145)

---

.github/workflows/test.yaml
.github/workflows/triggerConversion.yml

- enable conversion to cloud-hosted guide and enable PR checker
- include PR: #148

Create triggerConversion.yml and update test.yml

---

.github/workflows/test.yaml
.github/workflows/triggerConversion.yml

* Fixing related guides section.
* fixing links in guide
* Fixing hotspots
* Adding Action for cloud-hosted-guides
* Create triggerConversion.yml
* Update test.yaml
Co-authored-by: jakub-pomykala <56261244+jakub-pomykala@users.noreply.github.com>
Co-authored-by: Jakub F Pomykala <Jakub.Pomykala@ibm.com>

Merge qa to master: Create triggerConversion.yml and update test.yml (#149)

---

README.adoc

PR: #154 
update cloud-hosted guide instructions to remove the links from https://yourname-9090.theiadocker-4.proxy.cognitiveclass.ai/

Merge qa to master: Update README.adoc (#154)

---

README.adoc
finish/frontend/src/main/webapp/index.xhtml
start/frontend/src/main/webapp/index.xhtml

To make the cloud-hosted guide more smoothly, add a login link at the index.xhtml

Add a login link 

---

README.adoc
finish/frontend/src/main/webapp/index.xhtml
start/frontend/src/main/webapp/index.xhtml

PR: #156 
update cloud-hosted guide instructions to remove the links from `https://yourname-9090.theiadocker-4.proxy.cognitiveclass.ai/`

Merge qa to master: Update README.adoc (#156)
